### PR TITLE
Fix issue where plugin file is not being deleted

### PR DESCRIPTION
**Pull request by mitch-roblox**

### CODE REVIEW

**Comment by Brantone** [comment]
Does it need version bump? Or over-write existing?

**Comment by mitch-roblox** [comment]
I usually leave that to the upstream cookbook, tbh. I'm going to submit a PR there, but since it's a Chef-managed cookbook the process is a bit thick and in the short-term I just want to get rid of a hack in rblx_elasticsearch by reference our own branch.

Bad idea? Some other way I should be approaching?

**Comment by Brantone** [comment]
Makes sense. With some of the other community cookbooks I had bumped the minor version, then re-adjusted if if the upstream PR gets merged. The trick is if the same version for upstream cookbook more changes. It's a `berks upload --force` either way :(

**Comment by mitch-roblox** [comment]
Yeah, exactly. Doesn't feel like there's a good pattern for dealing with this. I figure when they release the upstream one it'll get a new version and I can update to use that, then we an just delete our Roblox-specific version from Chef server when it's no longer being referenced.

**Comment by Brantone** [comment]
Might still be worth a version bump on this one as an indicator of Roblox != Community ... until the Community one is updated, which even if it takes a while will live as an indicator until that time.

**Comment by mitch-roblox** [comment]
Ok, done.

**Pull request merged**
